database:
  host: localhost
  port: 5432
  username: postgres
  name: bagel

logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    simple:
      format: >-
        {
          'time': %(asctime)s,
          'module_name': %(module)s,
          'level': %(levelname)s,
          'pid': %(process)s,
          'thread': %(threadName)s,
          'loggerName': %(name)s,
          'message': %(message)s
        }

  handlers:
    default:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: consumer.log
      interval: 1
      when: h

    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

  loggers:
    ConsumerWorker:
      level: INFO
      handlers: [default, console]

  root:
    level: INFO
    handlers: [default]
